# Generated by Django 4.1.7 on 2023-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_submission_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.CharField(default='notes', max_length=100),
        ),
    ]
